name: 'DevOpsify Check'
description: 'Download and run the latest check-cli tool.'
runs:
  using: 'composite'
  steps:
    - name: Download latest check-cli release
      shell: bash
      run: |
        set -e
        OS=$(uname -s)
        ARCH=$(uname -m)
        if [[ "$OS" == "Linux" && "$ARCH" == "x86_64" ]]; then
          ASSET="check-linux-amd64"
        elif [[ "$OS" == "Linux" && "$ARCH" == "aarch64" ]]; then
          ASSET="check-linux-arm64"
        elif [[ "$OS" == "Darwin" && "$ARCH" == "x86_64" ]]; then
          ASSET="check-macos-intel"
        elif [[ "$OS" == "Darwin" && "$ARCH" == "arm64" ]]; then
          ASSET="check-macos-arm64"
        elif [[ "$OS" == MINGW* || "$OS" == CYGWIN* || "$OS" == MSYS* ]]; then
          ASSET="check.exe"
        else
          echo "Unsupported OS/ARCH: $OS/$ARCH"
          exit 1
        fi

        LATEST_URL=$(curl -sL https://api.github.com/repos/devopsifyco/check-cli/releases/latest | grep browser_download_url | grep "$ASSET" | cut -d '"' -f 4)
        echo "Downloading $LATEST_URL"
        curl -L "$LATEST_URL" -o check-download

        if [[ "$ASSET" == "check.exe" ]]; then
          mv check-download check.exe
        else
          mv check-download check
          chmod +x check
        fi
    - name: Run check help
      shell: bash
      run: |
        if [[ -f check.exe ]]; then
          ./check.exe help
        else
          ./check help
        fi 