name: Validate DevOpsify Check Action
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  check-action-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check help
        uses: ./check
        with:
          args: 'help'

      - name: Check latest version istio
        uses: devopsifyco/actions/check
        with:
          args: 'version istio'

      - name: Check CVEs of version postgresql 16.4
        uses: devopsifyco/actions/check@develop
        with:
          args: 'version postgresql 16.4 --cve'

      - name: Run DevOpsify Check Count Line Of Code
        run: |
          ./checkctl code loc

      - name: Run DevOpsify Check Deps
        run: |
          ./checkctl code deps .