name: Test DevOpsify Check Action
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  check-action-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use DevOpsify Check
        uses: ./check