name: Test DevOpsify Check Action
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  check-action-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check CLI version
        uses: devopsifyco/actions/check@develop
        with:
          args: 'version istio'

      - name: Check CVE version postgresql 16.4
        uses: ./check
        with:
          args: 'version postgresql 16.4 --cve'